quarkus:
  application:
    name: incident-service
  log:
    level: INFO
    console:
      enable: true
      level: DEBUG
    category: 
      "com.redhat.cajun.navy":
         level: DEBUG
      "org.eclipse.yasson":
        level: ERROR
  datasource:
    db-kind: mariadb
    jdbc:
      driver: org.mariadb.jdbc.Driver
      url: ${RDBMS_URL}
      min-size: 5
      max-size: 20
      initial-size: 5
      validation-query-sql: SELECT 1
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PWD}
  hibernate-orm:
    database:
      generation: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
  kafka:
    health:
      enabled: true
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP}
mp:
  messaging:
    incoming:
      incident-update-location:
        connector: smallrye-kafka
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.labmonkeys.cajun_navy.incident.event.IncidentDtoDeserializer
        request:
          timeout:
            ms: 3000
        enable: 
          auto:
            commit: false
      incident-update-status:
        connector: smallrye-kafka
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.labmonkeys.cajun_navy.incident.event.IncidentDtoDeserializer
        request:
          timeout:
            ms: 3000
        enable: 
          auto:
            commit: false
      incident-assigned:
        connector: smallrye-kafka
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.labmonkeys.cajun_navy.incident.event.IncidentDtoDeserializer
        request:
          timeout:
            ms: 3000
        enable: 
          auto:
            commit: false
    outgoing:
      incident-updated:
        connector: smallrye-kafka
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        acks: 1
      incident-reported:
        connector: smallrye-kafka
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        acks: 1
